name: Fabricar Biblia Lite
on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Flet
        run: pip install flet --upgrade

      - name: Compilar APK (Bajo Peso)
        run: |
          # Solo para arquitectura moderna para que pese 50MB
          yes | flet build apk --target-architecture android-arm64

      - name: Entregar APK Final
        uses: actions/upload-artifact@v4
        with:
          name: Biblia_Lite_Instalable
          path: build/apk/*.apk
