name: Fabricar Biblia Final
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Preparar Android
        uses: android-actions/setup-android@v3

      - name: Instalar dependencias
        run: |
          pip install flet
          # Si tienes más librerías en requirements.txt, las instalamos aquí
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fabricar APK (Incluyendo Biblia.json)
        run: |
          # El comando --include-assets asegura que el JSON entre en el APK
          yes | flet build apk --include-assets Biblia.json

      - name: Entregar Archivo APK
        uses: actions/upload-artifact@v4
        with:
          name: MiBibliaInstalable
          path: build/apk/*.apk
